name: firstapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  permission_handler: ^11.0.0
  flutter_contacts: ^1.1.9+2
  http: ^0.13.5
  shared_preferences: ^2.1.1
  yaml: ^3.1.2
  dio: ^5.7.0
  provider: ^6.1.2
  get: ^4.6.6
  hive: ^2.2.3
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  mobile_scanner: ^6.0.2
  lucide_icons: ^0.257.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/
